### PR TITLE
add new utils functions

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by the-funnel** [comment]
@mairieli This is an alternative implementation that is not hacking into the createComponent. I would like to avoid that to make it more reusable and robust. This way we can totally decouple the StateContext and all the related components.

And it is using createHook so it's more Reakit-ish way.

**Comment by the-funnel** [comment]
@mairieli  Just finished this up 😄 Tests are passing. I'll experiment with other components as well. Would like to hear your thoughts about this implementation.

**Comment by mairieli** [comment]
Duplicate of #2

**Comment by the-funnel** [comment]
@mairieli Not a duplicate, can you double check?

**Pull request closed without merging**
